### ISSUE TITLE
Dependencies includes options

### ISSUE THREAD

**Issue by bibraheem** [Daryes/rundeck-dependencies-plugin#1]
Hi Daryes,
Can we use your plugin to cover the blocking between jobs according Option filter jobs
I mean, if we have a job to run on such server, it should be blocked by an option like same server and so on

**Comment by Daryes** [comment]
If I understand correctly the intent, a suitable example would be : 

- a job A with a step running on different servers (S1 to S5)
- a job B, linked to A but targeting the status for a specific server execution, S1 for example
- another job C  linked to A, server S2
- another job D linked to A, server S3
- ...

For this situation, currently the plugin look only for the job final status.
So it's not supported currently.
But as the Rundeck API returns this information in the job execution status, it could be implemented  :
````
      <successfulNodes>
        <node name='\''server 1'\'' />
        <node name='\''server 2'\'' />
      </successfulNodes>
````
The complete name, or a regex would be used as a filter. I'll get a look.

If it's a different case, I'll need more information.

**Comment by bibraheem** [comment]
Sorry If I causing some confusion,
My case like the below
For example I have two same job ProductBuild A1,A2
A1 is running , A2 come to run on the same S1
A2 should be blocked until A1 change the status (finish, fail, ...etc) and so on,
Thanks for your response

**Comment by Daryes** [comment]
I might be able to filter the target server, but only when using a manual launch using the "Prepare and run" => "Change the Target Nodes" option and setting the server names

**Comment by Daryes** [comment]
Get a look to the [v1.0.9](https://github.com/Daryes/rundeck-dependencies-plugin/releases/tag/1.0.9), it should do the trick.
Note that the node filter will only triggers when 'Change the Target Nodes' was selected at launch.
