### ISSUE TITLE
Skip job itself from dependency

### ISSUE THREAD

**Issue by bibraheem** [Daryes/rundeck-dependencies-plugin#2]
Can we skip job itself from dependency process?

**Comment by Daryes** [comment]
The question is not clear, do you have an example ?
Currently you have 2 modes for the dependency : 
- hardlink, which will always wait until the target job is started and completed (or aborted, depending of the status setting). If the target job didn't run at all, the wait will keep locking the job.
- softlink, which will wait only if the target job was running **_before_** the launch. If the target job wasn't already running, the dependency will exit without error.

If it's about exiting a dependency currently waiting, there's an integrated help in the output, you just have to create an empty file : 
`Shell command to skip this loop : touch  ...`
