### ISSUE TITLE
Error: cannot contact rundeck through the API

### ISSUE THREAD

**Issue by atuvida** [Daryes/rundeck-dependencies-plugin#3]
Hi,
I'm getting the below error when I tried testing this plugin.

Error: cannot contact rundeck through the API
--

<result error='true' apiversion='31'><error code='unauthorized'><message>(unauthenticated) is not authorized for: /api/1/projects</message></error></result>
--

Script result code was: 1
--

Maybe I missed something in properly setting it up?
Here's what I did based on the instructions from here:
-downloaded rundeck-dependencies-plugin-master.zip and saved it in /var/lib/rundeck/libext/
then chown it to rundeck:rundeck
-generated a non expiry token from the admin account so it sure has read access to all projects
-saved the api token to /etc/rundeck/profile as export RD_TOKEN='api token here..'

and this is my workflow step using this dependency plugin:

1: Workflow step executing: StepExecutionItem{type='dependencies-wait_job', keepgoingOnSuccess=false, hasFailureHandler=false}
06:41:26 |   |   | [dependencies-wait_job] step started, config: {optional_params=, target_job=testjob1, node_filtering=adapt, softlink=-hardlink, target_project=TestProject, target_group=TEST, force_launch=, status_job=success}
06:41:26 |   |   | [dependencies-wait_job] executing: [/bin/bash, /var/lib/rundeck/libext/cache/rundeck-dependencies-plugin-master/dep_wait_job.sh, -project, TestProject, -group, TEST, -job, testjob1, -state, success, -hardlink, -node_filtering, adapt, , ]
06:41:26 |   |  

can anyone guide me where to go or what to check from here? I'd appreciate it.
Thanks

**Comment by Daryes** [comment]
It's seems rundeck isn't keeping the /etc/rundeck/profile in the environment anymore, nor loading the user .profile
Edit the /etc/init.d/rundeckd file, and in the `start)` section with :
```
        start-stop-daemon --start --quiet --chuid $USER:$USER \
                    --make-pidfile --pidfile $PIDFILE \
                    --background --startas /bin/bash -- \
                    -c "exec $DAEMON_EXEC >> $LOG 2>&1"
```

Add to the `-c exec` line a `-l` in front, it will load the user profile.
```
-l -c "exec $DAEMON_EXEC >> $LOG 2>&1"
```

Then, add the token declaration to the rundeck user .profile : 
```
$ sudo su - rundeck
$ cd ~
$ grep -i "token" .profile
	export RD_TOKEN="......"
```
Don't forget to check the rundeck's home directory is set to 750.
It should be good after restarting the rundeck service.

I'll update the documentation and open a bug on Rundeck side

**Comment by atuvida** [comment]
Hi Daryes,

This is what the start() portion of my /etc/init.d/rundeck looks like:

start() {
        status -p $PID_FILE $prog >/dev/null
        RETVAL=$?
        if [ $RETVAL -eq 0 ]; then
                echo Already started.
                return $RETVAL
        fi
        echo -n $"Starting $prog: "
        if ! touch $servicelog; then
                echo No access to $servicelog. This usually means you need to be root
                echo_failure
                echo
                return 1
        fi
        nohup runuser -s /bin/bash -l rundeck -c "$rundeckd" >>$servicelog 2>&1 &
        RETVAL=$?
        PID=$!
        echo $PID > $PID_FILE
        if [ $RETVAL -eq 0 ]; then
                touch /var/lock/subsys/$prog
                echo_success
        else
                echo_failure
        fi
        echo
        return $RETVAL
}

I didn't add anything because it looks like the "-l" option is already there.
I noticed that I didn't have any .profile file for my rundeck user in ~ after I performed the commands 
 sudu su rundeck
cd ~

so I created a .profile file with permission 644 and added a line
export RD_TOKEN="rd token  here"

My rundeck's home is set to 750 too.
The RD_TOKEN was generated by the admin user for another user i.e. only the username's filled in on generate new token form.

I restarted rundeck service and tried running the job using the user who owns the token and then using the admin user but I'm still getting the same error for either of them.

I'm not sure what I missed.

I'm attaching my latest run's log output.

[testjob3-20190606-070706.txt](https://github.com/Daryes/rundeck-dependencies-plugin/files/3259365/testjob3-20190606-070706.txt)

Thanks

**Comment by Daryes** [comment]
This test is specifically done to check the availability of Rundeck and the validity of the authorization token.
```
23:07:07 [admin@octopus 1][ERROR] Error: cannot contact rundeck through the API
23:07:07 [admin@octopus 1][ERROR] <result error='true' apiversion='31'><error code='unauthorized'><message>(unauthenticated) is not authorized for: /api/1/projects</message></error></result>
```
The error is due to the token either not found in the environment, or not valid.  

For a quick check, do this :
```
sudo su - rundeck
echo $RD_TOKEN
```
If it's empty, that's why it's not working.
If the token is visible, check if it was created under the Rundeck administrator/operator account.

I'll upload a new version with an additional test for the token availability

Done, check the version [1.0.10](https://github.com/Daryes/rundeck-dependencies-plugin/releases/tag/v1.0.10)
It has an information line about the token, and will raise an error when missing.

**Comment by atuvida** [comment]
Hi,

I tried this as suggested. But after switching to rundeck user, performing an echo $RD_TOKEN command gives an empty output.
I tried running the job too and it gave an error saying RD_TOKEN is not found and I need to export it from /var/lib/rundeck/profile, and so I did then restarted rundeckd but got the same error and empty output on echo $RD_TOKEN command too.

So I went and traced the files rundeckd service seem to source.
The start() function along with some starting lines of my /etc/init.d/rundeckd is this:

#code excerpt starts here
prog="rundeckd"
RETVAL=0
PID_FILE=/var/run/${prog}.pid
servicelog=/var/log/rundeck/service.log

. /etc/rc.d/init.d/functions

. /etc/rundeck/profile

start() {
        status -p $PID_FILE $prog >/dev/null
        RETVAL=$?
        if [ $RETVAL -eq 0 ]; then
                echo Already started.
                return $RETVAL
        fi
        echo -n $"Starting $prog: "
        if ! touch $servicelog; then
                echo No access to $servicelog. This usually means you need to be root
                echo_failure
                echo
                return 1
        fi
        nohup runuser -s /bin/bash -l rundeck -c "$rundeckd" >>$servicelog 2>&1 &
        RETVAL=$?
        PID=$!
        echo $PID > $PID_FILE
        if [ $RETVAL -eq 0 ]; then
                touch /var/lock/subsys/$prog
                echo_success
        else
                echo_failure
        fi
        echo
        return $RETVAL
}
#code excerpt ends here

I tried exporting $RD_TOKEN e.g export RD_TOKEN="value here" inside /etc/rundeck/profile.
Still nothing.

/etc/rundeck/profile says not to add anything in it and to put additional and/or initial variables in /etc/sysconfig/rundeckd, and I did, but still nothing.

The only thing that seems to work is by exporting RD_TOKEN in /var/lib/rundeck/.bashrc.

There's another file inside /var/lib/rundeck that is named .bash_profile and I tried to add it there too, but it didn't work.

Note: every file I add, I chown to rundeck:rundeck and I always restart rundeckd for every change I made.

I'm not sure if what I did is the best way to do it but so far it works.

**Comment by Daryes** [comment]
It's one of the correct way, either the .profile or the .bash_rc in the Rundeck $HOME directory, depending of the shell.

The /etc/rundeck/profile file is used to build the command line to start Rundeck. It won't be reused for the environment inside Rundeck. I've removed the mention in the installation documentation.
